# Generated by Django 4.1.7 on 2023-03-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_id', models.IntegerField(error_messages={'unique': 'Мем с таким id уже создан.'}, unique=True)),
                ('text', models.TextField(error_messages={'unique': 'Мем с таким описанием уже создан.'}, unique=True, verbose_name='Текст мема')),
                ('image', models.ImageField(upload_to='mems/images', verbose_name='Мем')),
                ('image_url', models.URLField()),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('post_author', models.CharField(max_length=200, verbose_name='Автор мема')),
                ('likes_count', models.IntegerField(verbose_name='Количество лайков')),
            ],
            options={
                'verbose_name': 'Мем',
                'verbose_name_plural': 'Мемы',
                'ordering': ('-pub_date',),
            },
        ),
    ]
