# Generated by Django 4.1.5 on 2023-03-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mems_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='post_author',
            field=models.CharField(max_length=200, verbose_name='Автор мема'),
        ),
        migrations.AlterField(
            model_name='mem',
            name='text',
            field=models.TextField(error_messages={'unique': 'Мем с таким описанием уже создан.'}, unique=True, verbose_name='Текст мема'),
        ),
    ]
