# Generated by Django 4.1.5 on 2023-03-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mems_library', '0003_alter_mem_mem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='likes_count',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mem',
            name='mem_id',
            field=models.CharField(error_messages={'unique': 'Мем с таким id уже создан.'}, max_length=50, unique=True),
        ),
    ]
