# Generated by Django 4.1.5 on 2023-03-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mems_library', '0004_alter_mem_likes_count_alter_mem_mem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='image_url',
            field=models.URLField(max_length=300),
        ),
    ]
