# Generated by Django 4.1.7 on 2023-03-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mems_library', '0005_alter_mem_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mem',
            name='likes_count',
            field=models.IntegerField(verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='mem',
            name='mem_id',
            field=models.IntegerField(error_messages={'unique': 'Мем с таким id уже создан.'}, unique=True),
        ),
    ]
