# Generated by Django 4.1.7 on 2023-03-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mems_library', '0006_alter_mem_likes_count_alter_mem_mem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mem',
            name='image_url',
        ),
    ]
